version: "3"

services:
    app:
        build: ./app
        volumes:
            - /home/vova/script_files/topix:/root/script_files/topix
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        depends_on:
            - app
        ports:
            - "80:80"
