services:
    app:
        restart: always
        image: vova0911/topix:amd64_latest
        command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
        volumes:
            - /home/root/topix:/root/script_files/topix
    nginx:
        container_name: nginx
        restart: always
        image: vova0911/nginx_images:latest
        depends_on:
            - app
        ports:
            - 80:80

